mutation CustomerCreate($input: CustomerCreateInput!) {
  customerCreate(input: $input) {
    customer {
      firstName
      lastName
      email
      phone
    }
    customerUserErrors {
      code
      field
      message
    }
  }
}
