query AllOptions($first: Int!, $after: String) {
  products(first: $first, after: $after) {
    edges {
      node {
        options {
          name
          values
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
